# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38085b72abb25536a05f1f00044cb84f501d337f745a0190501c8cc3c40be12dc9cf80e8010c1a77e9b609114326fe0d78f927e62668046a1274feaec88b90a0

test:
  secret_key_base: 5de7fa7187a0705a7474802c2939d0ac71245cf25ccb8a575e8e3990e3dc14e6cb0fd809b174e74986fce97c35bec404fcc856130a9a688c026a95954783246a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
